### ISSUE TITLE
[Bug] Unable to login Mojang Account sometimes

### ISSUE THREAD

**Issue by riazufila** [VidTu/In-Game-Account-Switcher#7]
### Describe the bug

When I press login on Mojang accounts, it just waits and then no login is made.

### To Reproduce

1. Launch game.
2. Login a Mojang account.
3. Watch it fails to login successfully.

### Minecraft Version

Fabric 1.18.1

### Logs/Screenshots/Videos

```
[19:12:31] [Render thread/WARN]: Unable to login
ru.vidtu.ias.account.AuthException: ias.mojauth.unknown
	at ru.vidtu.ias.account.MojangAccount.refresh(MojangAccount.java:70) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at ru.vidtu.ias.account.MojangAccount.lambda$login$2(MojangAccount.java:40) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:12:57] [Render thread/WARN]: Unable to login
ru.vidtu.ias.account.AuthException: ias.mojauth.unknown
	at ru.vidtu.ias.account.MojangAccount.refresh(MojangAccount.java:70) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at ru.vidtu.ias.account.MojangAccount.lambda$login$2(MojangAccount.java:40) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:13:03] [Render thread/WARN]: Unable to login
ru.vidtu.ias.account.AuthException: ias.mojauth.unknown
	at ru.vidtu.ias.account.MojangAccount.refresh(MojangAccount.java:70) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at ru.vidtu.ias.account.MojangAccount.lambda$login$2(MojangAccount.java:40) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:14:19] [Render thread/WARN]: Unable to login
ru.vidtu.ias.account.AuthException: ias.mojauth.unknown
	at ru.vidtu.ias.account.MojangAccount.refresh(MojangAccount.java:70) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at ru.vidtu.ias.account.MojangAccount.lambda$login$2(MojangAccount.java:40) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:14:52] [Render thread/WARN]: Unable to login
ru.vidtu.ias.account.AuthException: ias.mojauth.unknown
	at ru.vidtu.ias.account.MojangAccount.refresh(MojangAccount.java:70) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at ru.vidtu.ias.account.MojangAccount.lambda$login$2(MojangAccount.java:40) ~[InGameAccountSwitcher-Fabric-1.18-7.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:15:10] [Render thread/INFO]: Stopping!
```

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by riazufila** [comment]
Also, just to add something, I'm using Fabric for 1.18.1 instead of 1.17.1. The modrinth page for this mod says there is a release for 1.18.1 and that is what I'm using. However, the bug report didn't list 1.18.1 as one of the releases.

**Comment by Timong-craft** [comment]
You don't need Mojang Login anymore because you can't play online with them

**Comment by riazufila** [comment]
Nevermind. This issue was only legit before the migration. Closed.
